In [32]:
import pandas as pd

In [33]:
# CSV File


df = pd.read_csv("employee_data.csv")
print(df, type(df))

   Employee_ID          Name    Department  Age  Salary  Experience_Years
0          101  Aarav Sharma   Engineering   28   85000                 4
1          102   Priya Verma            HR   32   62000                 7
2          103   Rahul Singh  Data Science   26   95000                 3
3          104   Sneha Patel   Engineering   30   88000                 5
4          105    Amit Kumar       Finance   35   72000                10
5          106    Neha Gupta     Marketing   27   68000                 2
6          107    Vikram Rao  Data Science   31   99000                 6
7          108    Ananya Das            HR   29   64000                 4
8          109   Karan Mehta   Engineering   25   78000                 2
9          110   Ishita Jain       Finance   33   81000                 8 <class 'pandas.core.frame.DataFrame'>

In [34]:
# F1 Datasets

df = pd.read_csv("archive/drivers.csv")
# print(df)

# print head
print(df.describe())

         driverId
count  861.000000
mean   431.061556
std    248.793797
min      1.000000
25%    216.000000
50%    431.000000
75%    646.000000
max    862.000000

In [35]:
# Selecting the data


df[["driverRef", "nationality"]]

      driverRef    nationality
0      hamilton        British
1      heidfeld         German
2       rosberg         German
3        alonso        Spanish
4    kovalainen        Finnish
..          ...            ...
856    sargeant       American
857      lawson  New Zealander
858     bearman        British
859   colapinto   Argentinian
860      doohan     Australian

[861 rows x 2 columns]

In [36]:
df

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...
856,858,sargeant,2,SAR,Logan,Sargeant,2000-12-31,American,http://en.wikipedia.org/wiki/Logan_Sargeant
857,859,lawson,30,LAW,Liam,Lawson,2002-02-11,New Zealander,http://en.wikipedia.org/wiki/Liam_Lawson
858,860,bearman,38,BEA,Oliver,Bearman,2005-05-08,British,http://en.wikipedia.org/wiki/Oliver_Bearman
859,861,colapinto,43,COL,Franco,Colapinto,2003-05-27,Argentinian,http://en.wikipedia.org/wiki/Franco_Colapinto
860,862,doohan,61,DOO,Jack,Doohan,2003-01-20,Australian,http://en.wikipedia.org/wiki/Jack_Doohan